<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <EmbeddedResource Include="../Database/Database.sql" LogicalName="QLKhachSan.Database.sql" />
    <EmbeddedResource Update="Assets/hotel-room.jpg" LogicalName="QLKhachSan.Assets.hotel-room.jpg" />
    <EmbeddedResource Include="Assets/hotel-room.jpg" LogicalName="QLKhachSan.Assets.hotel-room.jpg" />
  </ItemGroup>

</Project>
